apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: christapherantony/admin
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: careerconnect
            - name: MONGO_URI
              value: 'mongodb://admin-mongo-srv:27017'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: careerconnect-jwt-secret
                  key: JWT_KEY
# jwt environment from kubernetees secret obj
---
apiVersion: v1
kind: Service
metadata:
  name: admin-srv
spec:
  selector:
    app: admin
  ports:
    - name: admin
      protocol: TCP
      port: 3000
      targetPort: 3000
