apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers: 
        - name: auth
          image: christapherantony/auth
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: careerconnect
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017'
            - name: MONGO_URI_ATLAS
              valueFrom:
                secretKeyRef:
                  name: careerconnect-mongo-uri
                  key: MONGO_URI_ATLAS
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: careerconnect-jwt-secret
                  key: JWT_KEY
            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: careerconnect-gmail-secret
                  key: GMAIL_PASSWORD
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: careerconnect-admin-secret
                  key: ADMIN_PASSWORD
            - name: GOOGLEOAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: careerconnect-google-oauth
                  key: CLIENT_SECRET
            - name: GOOGLEOAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: careerconnect-google-oauth
                  key: CLIENT_ID
# jwt environment from kubernetees secret obj
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
