apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: christapherantony/profile
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: careerconnect
            - name: MONGO_URI
              value: 'mongodb://profile-mongo-srv:27017'
            - name: MONGO_URI_ATLAS
              valueFrom:
                secretKeyRef:
                  name: careerconnect-mongo-uri
                  key: MONGO_URI_ATLAS
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: careerconnect-cloudinary-config
                  key: CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: careerconnect-cloudinary-config
                  key: API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: careerconnect-cloudinary-config
                  key: API_SECRET
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: careerconnect-jwt-secret
                  key: JWT_KEY
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
# jwt environment from kubernetees secret obj
---
apiVersion: v1
kind: Service
metadata:
  name: profile-srv
spec:
  selector:
    app: profile
  ports:
    - name: profile
      protocol: TCP
      port: 3000
      targetPort: 3000
