apiVersion: apps/v1
kind: Deployment
metadata:
  name: skilltest-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: skilltest
  template:
    metadata:
      labels:
        app: skilltest
    spec:
      containers:
        - name: skilltest
          image: christapherantony/skilltest
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: careerconnect
            - name: MONGO_URI
              value: 'mongodb://skilltest-mongo-srv:27017'
            - name: MONGO_URI_ATLAS
              valueFrom:
                secretKeyRef:
                  name: careerconnect-mongo-uri
                  key: MONGO_URI_ATLAS
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: careerconnect-jwt-secret
                  key: JWT_KEY
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
# jwt environment from kubernetees secret obj
---
apiVersion: v1
kind: Service
metadata:
  name: skilltest-srv
spec:
  selector:
    app: skilltest
  ports:
    - name: skilltest
      protocol: TCP
      port: 3000
      targetPort: 3000
